- scraper/parsing/amazon.py
- server/app/queue-handling/review.server.ts
- server/app/routes/product.$productId.tsx
- server/prisma/migrations/20230401071758_/migration.sql
- server/prisma/migrations/20230401073916_/migration.sql
- server/prisma/schema.prisma
Saving manufacturers and products
> Data source changes

- .idea/6monthslater.iml
- server/app/components/button.tsx
- server/app/components/footer.tsx
- server/app/components/navbar.tsx
- server/app/components/navlink.tsx
- server/app/root.tsx
- server/app/routes/_index.tsx
- server/app/routes/admin.queue-status.tsx
- server/app/routes/admin.queue.tsx
- server/package-lock.json
- server/package.json
- server/tailwind.config.js
Prep the UI enough that main UI development can commence.
Adds of main components:
- Navbar
- Footer
Adds reusable components:
- Button
- NavLink
Adds packages:
- `react-icons`
Updates packages:
- `vm2`
Redesigns pages:
- All of them
Modifies IntelliJ Config:
- Ignore build folders
Other changes:
- Add HTML title
- Add styles for all Tailwind containers
- The entire app is now a flexbox
Fixes:
- Queue Status page continuing to refresh after navigating away
> feat(ui): setup ui

- server/app/components/footer.tsx
- server/app/components/navbar.tsx
- server/app/components/navlink.tsx
- server/app/routes/admin.crawler.tsx
- server/app/routes/admin.reviews.($pageNum).tsx
Navbar:
- Semibold link on hover
- Underline active link
- Remove redundant class name
Footer:
- Remove period
Pages from #19 were redone to match the rest of the pages
> feat(ui): update navbar, footer, and #19 page styles

- server/app/components/button.tsx
- server/app/routes/_index.tsx
- server/app/routes/admin.queue-status.tsx
- server/app/routes/product.$productId.tsx
- server/app/types/TremorBarListData.ts
feat: basic implementation of product page
> feat(ui): product page

- server/app/routes/product.$productId.tsx
> feat: fix inability to do elementary subtraction

- README.md
- scraper/parsing/amazon.py
- scraper/tests/parser/test_amazon.py
> Fix order of install instructions and fix outdated parser

- .github/workflows/pytest.yaml
- README.md
- scraper/.env.example
- scraper/parsing/amazon.py
- scraper/requester/request_maker.py
- scraper/requirements.txt
- scraper/tests/parser/test_amazon.py
- scraper/utils/env.py
Solves issue with scraper failing on GitHub actions
> Scrape using predefined cookie

- scraper/utils/env.py
I forgot to use the defaults object in the get env function
> Fix default cookie not actually being used

- scraper/analyzer/analyzer.py
- scraper/crawler/amazon.py
- scraper/listener/analyzer.py
- scraper/listener/crawler.py
- scraper/listener/parser.py
- scraper/utils/env.py
- server/app/queue-handling/review.server.ts
- server/app/routes/admin.products.($pageNum).tsx
Fix issues discovered while running the scraper on different products
> Crawler fixes

- server/app/queue-handling/review.server.ts
- server/app/routes/admin.product.$productId.tsx
- server/app/routes/product.$productId.tsx
- server/prisma/migrations/20231106034657_add/migration.sql
- server/prisma/schema.prisma
Depends on #66 
Product page now displays top issues with links to their corresponding review.
> Integrate product page with analyzer data

- .github/workflows/pytest.yaml
- docker/rabbitmq.conf
- scraper/.gitignore
- scraper/README.md
- scraper/analyzer/train_issue_detection.json
- scraper/grammar-3.gbnf
- scraper/listener/analyzer.py
- scraper/requirements.txt
- scraper/setup.sh
- scraper/utils/env.py
Depends on #67 
Closes #70
The analyzer can now generate training data using the LLAMA large language model and real-world reviews. This generates a JSON file that can be used in `analyzer/train_issue_detection.json`, but the data must be human reviewed as it is not fully accurate.
Training the analyzer using the large language model allows us to use the power of the large language model without the speed and resource consumption issues of the large language models. Our analyzer is very quick, and is up to 60 times faster than using LLAMA directly.
> Add training system to analyzer

- scraper/parsing/amazon.py
- scraper/tests/analyzer/test_analyzer.py
- scraper/tests/parser/test_amazon.py
- server/app/queue-handling/review.server.ts
- server/prisma/migrations/20231120060736_add_product_image_url/migration.sql
- server/prisma/schema.prisma
Before it was always using the utc now timestamp
> Fix scraper from scraping the wrong date and parse product images

- server/app/queue-handling/review.server.ts
> Improve error message for when queue is not able to connect

- server/prisma/migrations/20231120060736_add_product_image_url/migration.sql
Fixes error about `image_url` column being missing
> Fix migration not having default value

- .github/workflows/build-images.yml
Fixes docker build workflow not running
> Request packages write permission

- server/app/routes/_index.tsx
No more browser autocomplete UI blocking it, and it now only shows products with issues
> Suggestion box changes

- server/app/components/navbar.tsx
- server/app/routes/product.$productId.tsx
- Fix #101
- Fix columns overflowing off screen
- Fix #100
- Fix #104
> fix: buggy columns on product page

- server/app/routes/product.$productId.tsx
> Filter out duplicates from top issues and fix top issues sometimes having more than 5

- server/app/routes/auth.signup.tsx
In docker, the request url came from "localhost" even in prod. Appears to be an issue with the docker container not knowing where it is.
> Fix redirect url in email from sign up being incorrect

- server/app/routes/admin.products.tsx
> Fix clear reports button not clearing all reports

- server/app/routes/admin.products.tsx
> feat: add direct link to product from admin products page
